import Header from "@/components/header/header";
import "./globals.css";
import Footer from "@/components/footer/footer";
import { Heebo } from 'next/font/google';

const heebo = Heebo({ subsets: ['latin'] });

export const metadata = {
  title: "Meta Capital",
  description: "Generated by Meta Capital",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        <link rel="icon" href="/Logo.png" type="image/png" />
      </head>
      <body className={`${heebo.className} antialiased`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
