import Header from "@/components/header/header";
import "./globals.css";
import Footer from "@/components/footer/footer";
import { Heebo } from 'next/font/google';

const heebo = Heebo({ subsets: ['latin'] });

export const metadata = {
  title: "Meta Capital",
  description: "Generated by Meta Capital",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        <meta property="og:title" content={metadata.title} />
        <meta property="og:description" content={metadata.description} />
        <meta property="og:image" content="/Logo.png" />
        <meta property="og:url" content="https://www.metacap.finance/" />
      </head>
      <body className={`${heebo.className} antialiased`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
